spring.application.name=Encryption-postgreSQL
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost/Encryption-postgreSQL
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.driverClassName=${DB_DRIVER:org.postgresql.Driver}


# Server port
server.port=8080